In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

In [2]:
pip install openpyxl

Requirement already satisfied: openpyxl in d:\dev_work\coorpost\coorpost_env\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in d:\dev_work\coorpost\coorpost_env\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:

# Read an Excel (.xls or .xlsx) file
df = pd.read_excel("Rastriya Prajatantra Party - राप्रपा _language.xlsx")

# Show first 5 rows
print(df.head())

     user/name                                                url Language  \
0  RppforNepal  https://www.facebook.com/RppforNepal/posts/pfb...   Nepali
1  RppforNepal     https://www.facebook.com/reel/765670929203948/   Nepali
2  RppforNepal  https://www.facebook.com/RppforNepal/posts/pfb...   Nepali
3  RppforNepal  https://www.facebook.com/RppforNepal/posts/pfb...   Nepali
4  RppforNepal  https://www.facebook.com/RppforNepal/posts/pfb...   Nepali

    likes  shares
0   174.0     7.0
1  1844.0   122.0
2   324.0    14.0
3   412.0    28.0
4   249.0    38.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 370 entries, 0 to 369
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   user/name  370 non-null    object
 1   url        370 non-null    object
 2   Language   370 non-null    object
 3   likes      124 non-null    float64
 4   shares     124 non-null    float64
dtypes: float64(2), object(3)
memory usage: 14.6+ KB

In [5]:
df["likes"] = df["likes"].replace("", None).fillna(400)
df["shares"] = df["shares"].replace("", None).fillna(257)

In [6]:


now = pd.Timestamp.now()
start = now - pd.Timedelta(days=7)

# Generate random valid timestamps as pandas Timestamps
random_times = pd.to_datetime(
    start + (now - start) * np.random.rand(len(df))
)

df["timestamp"] = random_times

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 370 entries, 0 to 369
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   user/name  370 non-null    object
 1   url        370 non-null    object
 2   Language   370 non-null    object
 3   likes      370 non-null    float64
 4   shares     370 non-null    float64
 5   timestamp  370 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 17.5+ KB

In [8]:
# Add incremental unique post_id starting from 1
df["post_id"] = range(1, len(df) + 1)

In [9]:
cols = ["post_id"] + [col for col in df.columns if col != "post_id"]
df = df[cols]

In [10]:
df = df.rename(columns={
    "post_id": "post_id",
    "user/name": "page_id",
    "url": "shared_url",
    "timestamp": "created_time",
    "likes": "likes",
    "shares": "shares"
})

In [11]:
df_selected = df[["post_id", "page_id", "shared_url", "created_time", "likes", "shares"]]

In [12]:
df_selected.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 370 entries, 0 to 369
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   post_id       370 non-null    int64
 1   page_id       370 non-null    object
 2   shared_url    370 non-null    object
 3   created_time  370 non-null    datetime64[ns]
 4   likes         370 non-null    float64
 5   shares        370 non-null    float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 17.5+ KB

In [13]:
display(df_selected)

,post_id,page_id,shared_url,created_time,likes,shares
0,1,RppforNepal,https://www.facebook.com/RppforNepal/posts/pfb...,2026-01-21 14:19:17.356906627,174.0,7.0
1,2,RppforNepal,https://www.facebook.com/reel/765670929203948/,2026-01-18 22:10:57.701334828,1844.0,122.0
2,3,RppforNepal,https://www.facebook.com/RppforNepal/posts/pfb...,2026-01-19 12:03:05.178213164,324.0,14.0
3,4,RppforNepal,https://www.facebook.com/RppforNepal/posts/pfb...,2026-01-15 03:20:59.595861190,412.0,28.0
4,5,RppforNepal,https://www.facebook.com/RppforNepal/posts/pfb...,2026-01-17 18:04:31.563759946,249.0,38.0
...,...,...,...,...,...,...
365,366,vhpnepal,https://www.facebook.com/vhpnepal/posts/pfbid0...,2026-01-16 11:14:36.204160089,400.0,257.0
366,367,vhpnepal,https://www.facebook.com/vhpnepal/posts/pfbid0...,2026-01-19 16:46:31.234960008,400.0,257.0
367,368,vhpnepal,https://www.facebook.com/vhpnepal/posts/pfbid0...,2026-01-15 09:12:24.378764853,400.0,257.0
368,369,vhpnepal,https://www.facebook.com/vhpnepal/posts/pfbid0...,2026-01-17 18:05:05.221701676,400.0,257.0
369,370,vhpnepal,https://www.facebook.com/vhpnepal/posts/pfbid0...,2026-01-15 04:29:39.772853200,400.0,257.0

In [14]:
df_selected.to_csv("posts_data.csv", index=False, mode="w")

In [15]:
df2 = pd.read_csv("posts_data.csv")

In [16]:
display(df2)

,post_id,page_id,shared_url,created_time,likes,shares
0,1,RppforNepal,https://www.facebook.com/RppforNepal/posts/pfb...,2026-01-21 14:19:17.356906627,174.0,7.0
1,2,RppforNepal,https://www.facebook.com/reel/765670929203948/,2026-01-18 22:10:57.701334828,1844.0,122.0
2,3,RppforNepal,https://www.facebook.com/RppforNepal/posts/pfb...,2026-01-19 12:03:05.178213164,324.0,14.0
3,4,RppforNepal,https://www.facebook.com/RppforNepal/posts/pfb...,2026-01-15 03:20:59.595861190,412.0,28.0
4,5,RppforNepal,https://www.facebook.com/RppforNepal/posts/pfb...,2026-01-17 18:04:31.563759946,249.0,38.0
...,...,...,...,...,...,...
365,366,vhpnepal,https://www.facebook.com/vhpnepal/posts/pfbid0...,2026-01-16 11:14:36.204160089,400.0,257.0
366,367,vhpnepal,https://www.facebook.com/vhpnepal/posts/pfbid0...,2026-01-19 16:46:31.234960008,400.0,257.0
367,368,vhpnepal,https://www.facebook.com/vhpnepal/posts/pfbid0...,2026-01-15 09:12:24.378764853,400.0,257.0
368,369,vhpnepal,https://www.facebook.com/vhpnepal/posts/pfbid0...,2026-01-17 18:05:05.221701676,400.0,257.0
369,370,vhpnepal,https://www.facebook.com/vhpnepal/posts/pfbid0...,2026-01-15 04:29:39.772853200,400.0,257.0